version: "3.9"
services:
  redis:
    image: "redis:alpine"
  server:
    build: ./server
  client1:
    build: ./client
    environment:
      - CLIENT_ID=alpha
  client2:
    build: ./client
    environment:
      - CLIENT_ID=beta
